version: 2
updates:

- package-ecosystem: "pip"
  directories:
    - "/"
    - "/examples/"
  schedule:
    interval: "weekly"
  groups:
    dependencies:
      patterns:
        - "*"

- package-ecosystem: "pip"
  directories:
    - "/tests/"
  schedule:
    interval: "monthly"
  groups:
    pytest:
      patterns:
        - "*"

- package-ecosystem: "pip"
  directories:
    - "/docs/"
  schedule:
    interval: "monthly"
  groups:
    sphinx:
      patterns:
        - "*"