name: Docs
on:
  push:
    tags:
      - v*
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: >
          pip install -e . &&
          pip install
          sphinx==5.3.0
          sphinx_rtd_theme==1.1.1
          sphinxcontrib-napoleon==0.7
          myst-parser==0.18.1
          sphinx-toolbox==3.2.0
          sphinx-autoapi==2.0.0
          nbsphinx==0.8.9
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
